site:
  url: "your_app_site"

huginn:
  url: "your_huginn_site"
  webrequest:
    telegraph: "telegraph_url"
    weibo: "weibo_url"
    twitter: "twitter_url"
    zhihu: "zhihu_url"
    douban: "douban_url"

authorization:
  twitter:
    app_key: "your_app_key"

telegram:
  bot_key: "your_telegram_bot_key"