site:
  url: "api.aturret.top"

huginn:
  url: "huginn.aturret.top"
  webrequest:
    telegraph: "21/supersbshelley"
    weibo: "56/shelleysmummydied"
    twitter: "60/shelleysdaddydied"
    zhihu: "67/shelleyisanoobplayer"
    douban: "63/shelleysallfamiliesdied"

authorization:
  twitter:
    app_key: "AAAAAAAAAAAAAAAAAAAAANmlWAEAAAAAPk7fNFgO2P0Mg83ga4kVvF49ilI%3DL67pc1i9el1HNUo2vJOPFTts921jAd1QpFqp8XZYYIblJ7MLLU"

telegram:
  bot_key: "931723693:AAFN453UJxlrPX8ilzKL2bFp2---QNLRQrA"